AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS_S3_Ingestion_pipeline

  Sample SAM Template for AWS_S3_Ingestion_pipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 90

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: src.main.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
#      Events:
#        S3UploadTrigger:
#          Type: S3
#          Properties:
#            Bucket: aws-s3-ingestion-v2   # Existing bucket name
#            Events: s3:ObjectCreated:*    # Trigger on upload
#            Filter:
#              S3Key:
#                Rules:
#                  - Name: prefix
#                    Value: source/

Outputs:

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
